Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NRLAdmin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "NRLAdmin.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "NRL contact.";

            return View();
        }
    }
}

Controllers/PerformsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NRLAdmin.Models;

namespace NRLAdmin.Controllers
{
    public class PerformsController : Controller
    {
        private NRLEntities db = new NRLEntities();

        // GET: Performs
        public ActionResult Index(NRLAdmin.Models.Ladder modelLadder)
        {
            modelLadder.GetLadderInfo();
            return View(modelLadder);
            //var performs = db.Performs.Include(p => p.Team).OrderByDescending(p => p.Points);
            //return View(performs.ToList());
        }

        //public ActionResult Ladder(NRLAdmin.Models.Ladder modelLadder)
        //{
        //    //var performs = db.Performs.Include(p => p.Team);
        //    //var performsLadder = db.Performs.GroupBy(p => p.TeamID).Select(g => new
        //    // {
        //    //     //PerformID = g.Max(pc => pc.PerformID).ToString(),
        //    //     TeamID = g.Max(pc => pc.TeamID).ToString(),
        //    //     Points = g.Sum(pc => pc.Points).ToString(),
        //    //     Wins = g.Sum(pc => (Int32)(pc.Wins)).ToString(),
        //    //     Draws = g.Sum(pc => (Int32)(pc.Draws)).ToString(),
        //    //     Losts = g.Sum(pc => (Int32)(pc.Losts)).ToString()
        //    // } ).AsEnumerable();
        //    //return View(performsLadder.ToList());

        //    modelLadder.GetLadderInfo();
        //    return View(modelLadder);
        //}

        // GET: Performs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Perform perform = db.Performs.Find(id);
            if (perform == null)
            {
                return HttpNotFound();
            }
            return View(perform);
        }

        // GET: Performs/Create
        public ActionResult Create()
        {
            ViewBag.TeamID = new SelectList(db.Teams, "TeamID", "TeamName");
            return View();
        }

        // POST: Performs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PerformID,TeamID,Points,Wins,Draws,Losts")] Perform perform)
        {
            if (ModelState.IsValid)
            {
                db.Performs.Add(perform);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TeamID = new SelectList(db.Teams, "TeamID", "TeamName", perform.TeamID);
            return View(perform);
        }

        // GET: Performs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Perform perform = db.Performs.Find(id);
            if (perform == null)
            {
                return HttpNotFound();
            }
            ViewBag.TeamID = new SelectList(db.Teams, "TeamID", "TeamName", perform.TeamID);
            return View(perform);
        }

        // POST: Performs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PerformID,TeamID,Points,Wins,Draws,Losts")] Perform perform)
        {
            if (ModelState.IsValid)
            {
                db.Entry(perform).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TeamID = new SelectList(db.Teams, "TeamID", "TeamName", perform.TeamID);
            return View(perform);
        }

        // GET: Performs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Perform perform = db.Performs.Find(id);
            if (perform == null)
            {
                return HttpNotFound();
            }
            return View(perform);
        }

        // POST: Performs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Perform perform = db.Performs.Find(id);
            db.Performs.Remove(perform);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>NRL Admin</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@nrl.com">Support@nrl.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@nrl.com">Marketing@nrl.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome to NRL Admin. </h1>
    <p class="lead">The essential app for NRL staff.</p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

@*<div>
    @Html.ActionLink("Ladder", "Index", "Performs")<br />
    @Html.ActionLink("Games", "Index", "Games")<br />
    @Html.ActionLink("Teams", "Index", "Teams")<br />
    @Html.ActionLink("Players", "Index", "Players")<br />
    @Html.ActionLink("Careers", "Index", "Careers")<br />
</div>*@

<div class="row">
    <div class="col-md-6">
        <h2>@Html.ActionLink("Ladder", "Index", "Performs")</h2>
        <p>View the current standings and rankings of the teams in the league. </p>

    </div>
    <div class="col-md-6">
        <h2>@Html.ActionLink("Games", "Index", "Games")</h2>
        <p>Schedule, update and view the results of the games in the league. </p>

    </div>
    <div class="col-md-6">
        <h2>@Html.ActionLink("Players", "Index", "Players")</h2>
        <p>Manage the information and statistics of the players in the league.</p>

    </div>
    <div class="col-md-6">
        <h2>@Html.ActionLink("Teams", "Index", "Teams")</h2>
        <p>Create, edit and delete the teams in the league.</p>

    </div>


    